<a href="https://colab.research.google.com/github/marcosgomeslana/analise-comercial-python/blob/main/analise_comercial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import os
import pandas as pd


lista_arquivo = os.listdir("/content/drive/MyDrive/Vendas")

In [ ]:

table_total = pd.DataFrame()

for arquivo in lista_arquivo:

  if ("Vendas" in arquivo):
    table = pd.read_csv(f"/content/drive/MyDrive/Vendas/{arquivo}")
    table_total = pd.concat([table])

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,0,HL4379,Televisão,5,Gabriel,Thoni,6/30/2018,Curitiba,2500,NaN
1,7,HL2714,Tablet,2,Thays,Castro,3/7/2018,Curitiba,1600,NaN
2,22,HL1918,iPhone,3,Lucas,Rodrigues,10/8/2018,Curitiba,5300,NaN
3,28,HL1918,iPhone,3,Gabriel,Silva,8/21/2018,Curitiba,5300,NaN
4,59,HL4379,Televisão,3,Pedro,Conceição,5/16/2018,Curitiba,2500,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2018,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2018,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2018,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2018,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Vinícius,Antunes,12/10/2018,Curitiba,1400,NaN

In [ ]:


display(table_total)

In [ ]:
#Produto mais vendido (em quantidade)

table_produto = table_total.groupby('Produto').sum()
table_produto = table_produto[['Quantidade Vendida']].sort_values(by='Quantidade Vendida', ascending=False)
display(table_produto)

            Quantidade Vendida
Produto
iPhone                     595
Televisão                  483
Notebook                   284
SmartWatch                 221
Android                    216
Câmera                     197
Tablet                     155

In [ ]:
#Produto que mais faturou (em faturamento)

table_total['Faturamento'] = table_total['Quantidade Vendida'] * table_total['Preco Unitario']
table_faturamento = table_total.groupby('Produto').sum()
table_faturamento = table_faturamento[['Faturamento']].sort_values(by='Faturamento', ascending=False)
display(table_faturamento)

            Faturamento
Produto
iPhone          3153500
Televisão       1207500
Notebook         994000
Android          734400
Câmera           413700
SmartWatch       309400
Tablet           248000

In [ ]:
#Loja ou cidade que mais vendeu (em faturamento) gráfico/dashboard

table_city = table_total.groupby('Loja').sum()
table_city = table_city[['Faturamento']].sort_values(by='Faturamento', ascending=False)
display(table_city)

          Faturamento
Loja
Curitiba      7060500

In [ ]:
import plotly.express as px

grafico = px.bar(table_faturamento, x=table_faturamento.index, y='Faturamento')
grafico.show()